-- ==========================================
-- SHRI JALARAM JWELLERS - COMPLETE SETUP
-- ==========================================
-- This script combines schema, migrations, and initialization.
-- Run this in the Supabase SQL Editor for a fresh setup.

-- 1. CORE SCHEMA (Tables, Triggers, Profiles)
-- ==========================================
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone_number TEXT,
    default_address TEXT,
    default_pincode TEXT,
    is_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock INTEGER DEFAULT 0,
    media_url TEXT,
    is_active BOOLEAN DEFAULT true,
    is_trending BOOLEAN DEFAULT false,
    rating DECIMAL(3, 2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    customer_email TEXT,
    subtotal DECIMAL(10, 2) NOT NULL,
    shipping_fee DECIMAL(10, 2) DEFAULT 0,
    total_amount DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending',
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image_url TEXT
);

CREATE TABLE IF NOT EXISTS shipping_details (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    pincode TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT,
    state TEXT,
    shipping_partner TEXT DEFAULT 'deliveryone',
    tracking_id TEXT,
    estimated_delivery TEXT,
    serviceability_status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS banners (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT,
    image_url TEXT NOT NULL,
    link_url TEXT,
    position TEXT DEFAULT 'hero',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. MIGRATIONS (Settings & Enhancements)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key TEXT NOT NULL UNIQUE,
    value JSONB NOT NULL,
    type TEXT NOT NULL DEFAULT 'text',
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.banners 
ADD COLUMN IF NOT EXISTS subtitle TEXT,
ADD COLUMN IF NOT EXISTS cta_text TEXT DEFAULT 'Shop Now',
ADD COLUMN IF NOT EXISTS style_type TEXT DEFAULT 'default';

-- 3. TRIGGERS & FUNCTIONS
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DO $$ BEGIN
    CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
    CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
EXCEPTION WHEN others THEN NULL; END $$;

-- 4. INITIAL CLIENT DATA
-- ==========================================
INSERT INTO settings (key, value, type) VALUES
('site_name', '"Shri Jalaram Jwellers"', 'text'),
('site_description', '"Premium Artificial & Traditional Jewellery"', 'text'),
('contact_email', '"contact@shrijalaramjwellers.com"', 'text'),
('contact_phone', '"+91 9876543210"', 'text'),
('address', '"Main Market, Ahmedabad, Gujarat, India"', 'text'),
('theme_color_primary', '"#800000"', 'text'),
('theme_color_secondary', '"#FFD700"', 'text'),
('social_instagram', '"https://instagram.com/shrijalaramjwellers"', 'text'),
('social_whatsapp', '"https://wa.me/919876543210"', 'text'),
('currency', '"INR"', 'text')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO categories (name, slug, image_url) VALUES
('American Diamond', 'american-diamond', 'https://images.unsplash.com/photo-1598560912005-59765abc33e6?q=80&w=800&auto=format&fit=crop'),
('Kundan & Jadau', 'kundan', 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800&auto=format&fit=crop'),
('Oxidized Silver', 'oxidized', 'https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?q=80&w=800&auto=format&fit=crop'),
('Temple Jewellery', 'temple', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop'),
('Antique Gold', 'antique-gold', 'https://images.unsplash.com/photo-1613133310164-28399321307c?q=80&w=800&auto=format&fit=crop'),
('Earrings & Jhumkas', 'earrings', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop'),
('Necklace Sets', 'necklaces', 'https://images.unsplash.com/photo-1599643477877-537ef5278531?q=80&w=800&auto=format&fit=crop'),
('Bangles & Kadas', 'bangles', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800&auto=format&fit=crop')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, image_url = EXCLUDED.image_url;

INSERT INTO banners (title, subtitle, image_url, cta_text, link_url, style_type, is_active) VALUES
('Golden Glow', 'Discover our festive collection with timeless designs.', 'https://images.unsplash.com/photo-1573408302382-9014b0208e03?q=80&w=1200&auto=format&fit=crop', 'View Collection', '/products', 'wtflex_bold', true);
